name: Foobar Action

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-foobar-action.yaml'
      - '.github/actions/foobar/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-foobar-action.yaml'
      - '.github/actions/foobar/**'

permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  foobar-action:
    uses: SwanseaUniversityMedical/.github/workflows/pr-and-release-repo.yaml@v1.0.3-pr-and-release-repo-action
    with:
      job-name: foobar-action
      comment-release: true
      release-tag-format: 'v${version}-foobar-action'

  prefixed-foobar-action:
    uses: SwanseaUniversityMedical/.github/workflows/pr-and-release-repo.yaml@v1.0.3-pr-and-release-repo-action
    with:
      job-name: prefixed-foobar-action
      comment-release: true
      release-tag-format: 'foobar-action-v${version}'
